name: NexusAuctionHouse
version: '${project.version}'
main: cc.synkdev.nah.NexusAuctionHouse
api-version: '1.13'
authors: [ Synk ]
description: The easy auction house plugin you've looked for, and for free!
website: https://synkdev.cc
depend:
  - SynkLibs
  - Vault